research_destinations:
  description: Research and suggest travel destinations based on the user's preference for {preference}.
  expected_output: A list of destinations with brief descriptions.

analyze_budget:
  description: >
    Analyze the user's budget of {budget} for a {duration}-day trip. Ensure the budget is realistic based on location and number of travelers. If the budget is too low, suggest alternative cheaper destinations.
  expected_output: >
    A detailed budget breakdown, including spending limits for travel, accommodation, and activities. Additionally, provide budget-friendly destination recommendations if needed.

create_itinerary:
  description: Create a {duration}-day travel itinerary for the chosen destination, incorporating the budget constraints and user preferences.
  expected_output: A day-by-day itinerary with activities, accommodation suggestions, and estimated costs in INR( make sure propery currency is used.).